### ISSUE TITLE
As a board member i wanna be able to close our financial year

### ISSUE THREAD

**Issue by Kenny-Lacroix** [Brixel/HaSpMan#172]
**Is your feature request related to a problem? Please describe.**
At the end of august our financial year ends and has to be closed so that we can start preparing the "anual meeting for the members"

**Comment by vyruz1986** [comment]
This implies we have to introduce the concept of a financial year in our domain logic.
Financial years run from and to specific dates, and always encompass 12 complete months (e.g. september 1st 2022 to august 31 2023)

We need to be able to configure the month and date in which the financial year starts. We can then use that parameter to calculate which transaction belongs to which financial year.

We also need a UI which lists the financial  year in which transactions have been added. In this UI it must be possible to close a financial  year.

Closing a financial  year should have the following consequences:
- No more transactions can be added/edited for closed financial  years

For the yearly all members meeting, we need to be able to calculate totals for the past (closed) fiscal year, this is described in detail in #174.

**Comment by BerendWouters** [comment]
Am I correct in saying that we can have just one "active" fiscal year, and multiple "closed" ones?
Adding a transaction requires to have an "active" year, or can a new financial year be created after adding transactions for that year? I would say yes, because that gives us the most flexibility in managing these years and transactions. However, this introduces the hard requirement that fiscal years need to follow each other immediately, so no transaction is left out in the closing of a fiscal year.

**Comment by BerendWouters** [comment]
I've been thinking about this, and isn't the "Financial year" the aggregate root of a set of transactions? I don't see how or why we would separate this into multiple domains.
