### ISSUE TITLE
As a board member i want to have auto calculations for expenses and 'inkomsten'

### ISSUE THREAD

**Issue by Kenny-Lacroix** [Brixel/HaSpMan#174]
Have it do this for all the categories

**Comment by BerendWouters** [comment]
At first I was thinking about using a separate tool for this (PowerBI, plain old SQL scripts, ...), but maybe the "Materialized Views" technique used to calculate the bank account total (#78 ) can be used here too?

**Comment by BerendWouters** [comment]
Probably related to this: when opening the edit page of a bank account, the app crashes.

**Comment by vyruz1986** [comment]
I decided to go for a Grafana dashboard with the HaSpMan SQL database after all, mainly for the following reasons:
- More flexible for adding/changing data and visualizations
- Better looking than anything I could've made in the UI

Considerations around this solutions instead of materialized views:
- Grafana is now directly querying our database (with a read-only user), this means if we change the database schema this might break grafana dashboards. Perhaps a nice solution for this would be a GraphQL API, but I'd like to delay that until there's a need for that.
- As Grafana is querying the regular database tables, they queries might become slow as data accumulates. Note that with the current dashboard, queries are always filtered by financial year.

As a quick reference, here's a screenshot of the dashboard of our dev environment:
![image](https://github.com/Brixel/HaSpMan/assets/3620147/926267fa-9cb5-49bd-826c-d057b12fc4c8)
