### ISSUE TITLE
Financial year migration will fail in production

### ISSUE THREAD

**Issue by vyruz1986** [Brixel/HaSpMan#225]
See https://github.com/Brixel/HaSpMan/blob/74ec505336de52cfc0eef7ef03fff0fe03ad7786/Persistence/Migrations/20230728184205_TransactionsBelongToFinancialYear.cs#L13

This migration runs an SQL query which creates  a hardcoded financial year which align's with Brixels 2022-2023 financial year, and then adds all existing transactions to said year.
This was likely done under the assumption that we would deploy this to production before the financial year ended (31/8/2023).
However this was not the case, meaning that we now have transactions past 31/8/2023, which would also get added to the 2022-2023 fincancial year.

**Comment by BerendWouters** [comment]
Two ways forward:
- create a rather complex query that compares the received date's year with all existing years. This however also expects the next financial year to exist.
- run the migration, create a new year and update transactions with received date > 31/8/2023 to new financial year.
I'd go for option 2, because it's easier, introduces less risk.

**Comment by vyruz1986** [comment]
Worked around by performing manual migration as discussed in comment above
