### ISSUE TITLE
Initial transaction is can not a transaction

### ISSUE THREAD

**Issue by Kenny-Lacroix** [Brixel/HaSpMan#229]
**Describe the bug**
the initial transaction that is used to initiate the system if you already have a bank account is not supposed to be a transaction because now it shows erronous data in the grafana if there would have been an actual internal transfer

**Comment by vyruz1986** [comment]
I've updated the grafana dashboard to not show the 'internal bank transfer' transactions at all.
Since the goal of the dashboard is to present our finances for the past financial years to our members, we need to give a global overview of expenses and income, transfers between bank accounts (or the initial amount transaction for the same matter) should not be displayed, since the information we present during the annual general meeting is not shown per bank account.
