### ISSUE TITLE
As a user, I want an overview of the active memberships.

### ISSUE THREAD

**Issue by BerendWouters** [Brixel/HaSpMan#53]
One of the core features of HaspMan is managing members and memberships.

It should be easy to view the current active members, and their duration.

**Comment by BerendWouters** [comment]
A couple of suggestions:
- On the dashboard, show the amount of active members (in a card or alike, you know the fancy dashboard stuff)
- Add a filter in the members overview table

**Comment by vyruz1986** [comment]
> A couple of suggestions:
> 
> * On the dashboard, show the amount of active members (in a card or alike, you know the fancy dashboard stuff)
> * Add a filter in the members overview table

I suggest scoping this issue to the following:

**Title:** As an admin/board member, I want to get an overview of active/inactive members
**Description**: Add active/inactive filter capabilities to member overview list. In the table, the 'Membership expiration date' column should be added. 

I would keep dashboard functionality to a future story, as I consider this more a nice-to-have rather than a necessity at this point in time.

**Comment by vyruz1986** [comment]
This is what I have now, feedback would be awesome:
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/3620147/190877670-b42f3432-2419-4230-baae-4a218219993c.png">

I'll start working on the filter functionality tomorrow.

**Comment by vyruz1986** [comment]
Closed by #96
